---
kind: pipeline
type: docker
name: default

steps:
  - name: e2e
    image: node:10
    commands:
      - npm install
      - cp nightwatch.e2e.json nightwatch.json
      - npm run test:e2e
    environment:
      PROXY_GRAPHQL_SERVER: http://nodejs:4000
      VUE_APP_PIWIK_ENABLED: false
      VUE_APP_GRAPHQL_HTTP: http://nodejs:4000
      VUE_APP_GRAPHQL_WS: ws://nodejs:4000
      VUE_E2E_SERVER_URL: http://e2e:8080

  - name: unit
    image: node:10
    commands:
      - wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
      - sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google.list'
      - apt update && apt install -y google-chrome-stable
      - npm install

  - name: nginx
    image: plugins/docker
    settings:
      repo: phoenix741/passprotect-client
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      auto_tag: true

  - name: notify
    image: plugins/slack
    settings:
      webhook:
        from_secret: webhook
      channel: ci
    when:
      status: [ success, failure ]

services:
  - name: nodejs
    image: phoenix741/passprotect-server:develop
    environment:
      MONGODB_HOST: mongodb://mongodb:27017/passprotect
      MONGODB_DATABASE: passprotect
      NODE_ENV: production
      DEBUG: "App:*"

  - name: selenium
    image: selenium/standalone-chrome

  - name: mongodb
    image: mongo:4
